[site]
title = "Cheng Yang (杨承)"
brand = "ImYangC7"
description = "Undergraduate student at Hangzhou Dianzi University."
favicon = "/favicon.png"
last_updated = "December 5, 2025"

[author]
name = "Cheng Yang"
title = "Undergraduate Student"
institution = "Hangzhou Dianzi University"
avatar = "/yc.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "imyangc7@hdu.edu.cn"
google_scholar = "https://scholar.google.com/citations?user=y7xaiIgAAAAJ&hl=en"
github = "https://github.com/ImYangC7"

[features]
# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"
